

name: Test_Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # Runs a single command using the runners shell
      - name: Install_apt_tools
        run: |
          echo Installing apt tools
          apt update && apt install python3 python3-pip verilator -y --no-install-recommends

      - name: Install_pip_tools
        run: |
          echo Installing pip tools
          pip install cocotb cocotb_bus
      # Runs a set of commands using the runners shell
      - name: Run_tb
        run: |
          echo Running test
          verilator ./${{ github.workspace }}/design.v ./${{ github.workspace }}/tb.sv --timing -Wno-INITIALDLY -Wno-WIDTHEXPAND -Wno-TIMESCALEMOD
 
